image: texlive/texlive:latest
stages:
  - build
build_pdf:
  stage: build
  script:
    - apt-get update && apt-get install -y python3-pip python3-venv
    - python3 -m venv venv && . venv/bin/activate
    - pip install -r requirements.txt
    - python3 ./CONVERT/code.py
    - python3 ./CONVERT/convergence.py
    - latexmk -shell-escape -pdf COOKBOOK.tex
  artifacts:
    paths:
      - COOKBOOK.pdf
