jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Compile
        uses: xu-cheng/texlive-action@v3
        with:
          docker_image: ghcr.io/xu-cheng/texlive-full
          run: |
            apk add --no-cache py3-pip build-base
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python3 ./CONVERT/code.py
            python3 ./CONVERT/convergence.py
            latexmk -shell-escape -pdf COOKBOOK.tex
      - if: github.event_name == 'push'
        name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: COOKBOOK.pdf
          file: COOKBOOK.pdf
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
name: PDF
'on':
  - push
  - pull_request
