name: PDF
on: [ push ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile
        uses: xu-cheng/texlive-action@v2
        with:
          docker_image: ghcr.io/xu-cheng/texlive-full:20240901
          run: |
            latexmk -shell-escape -pdf COOKBOOK.tex
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: COOKBOOK.pdf
          asset_name: COOKBOOK.pdf
          tag: latest
          overwrite: true
