name: PDF
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile
        uses: xu-cheng/texlive-action@v2
        with:
          docker_image: ghcr.io/xu-cheng/texlive-full
          run: |
            apk add --no-cache py3-pip build-base
            pip install -r requirements.txt
            python3 ./CONVERT/code.py
            python3 ./CONVERT/convergence.py
            latexmk -shell-escape -pdf COOKBOOK.tex
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: COOKBOOK.pdf
          asset_name: COOKBOOK.pdf
          tag: latest
          overwrite: true
